kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      # 指定掛載的目錄
      - mountPath: "/usr/share/nginx/html/"
        name: mypd
  volumes:
    - name: mypd
      # 掛載 PVC "myclaim"
      persistentVolumeClaim:
        claimName: myclaim

