kind: Pod
apiVersion: v1
metadata:
  name: mypod
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      #- mountPath: "/usr/share/nginx/html/"
      - mountPath: "/usr/local/etc/test/"
        name: mypod
  volumes:
    - name: mypod
      persistentVolumeClaim:
        claimName: myclaim

