kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html/"
        name: mypod
  volumes:
    - name: mypod
      persistentVolumeClaim:
        claimName: myclaim

